export default {
  login: "RodCerB",
  id: 79221247,
  node_id: "MDQ6VXNlcjc5MjIxMjQ3",
  avatar_url: "https://avatars.githubusercontent.com/u/79221247?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/RodCerB",
  html_url: "https://github.com/RodCerB",
  followers_url: "https://api.github.com/users/RodCerB/followers",
  following_url: "https://api.github.com/users/RodCerB/following{/other_user}",
  gists_url: "https://api.github.com/users/RodCerB/gists{/gist_id}",
  starred_url: "https://api.github.com/users/RodCerB/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/RodCerB/subscriptions",
  organizations_url: "https://api.github.com/users/RodCerB/orgs",
  repos_url: "https://api.github.com/users/RodCerB/repos",
  events_url: "https://api.github.com/users/RodCerB/events{/privacy}",
  received_events_url: "https://api.github.com/users/RodCerB/received_events",
  type: "User",
  site_admin: false,
  name: "Rodrigo Braga",
  company: null,
  blog: "",
  location: "Brasil",
  email: null,
  hireable: null,
  bio: "Just a person who is fascinated by the capacity that programming allows to make dreams, desires, vision and ideas come true.",
  twitter_username: null,
  public_repos: 4,
  public_gists: 0,
  followers: 1,
  following: 1,
  created_at: "2021-02-17T18:21:44Z",
  updated_at: "2021-04-23T13:54:46Z"
};
